### PR TITLE
add LDAP authentication support.

### PR DESCRIPTION
**Pull request by kencharos**
1. add sbt dependencies for LDAP.
2. add LDAPAuthenticatior and test.
3. add LdapLoginController and sub login page view.
4. add LDAP ENV and fix message, config.
5. fix README about LDAP settings.

### CODE REVIEW

**Comment by roundrop** [comment]
@kencharos 
Thanks for your great work.
Does this PR suport LDAPS and StartTLS?

**Comment by kencharos** [comment]
@roundrop  I added ssl, tsl

**Comment by roundrop** [comment]
@kencharos Sorry for my late response.
I'll try it later.
Thanks!

**Comment by roundrop** [comment]
Merged, thanks!

**Pull request merged**
